/* ═══════════════════════════════════════════════════
   data.js — seed data & constants
   Prices reflect Kyiv florist market, 2025–2026 (₴).
   Photography: Pexels (free license).
═══════════════════════════════════════════════════ */

const FLOWERS_DATA = [
  { id:'f1', plate:'01', name:'Роза Эквадор', nameLat:'Rosa × hybrida',
    img:'https://images.pexels.com/photos/1210009/pexels-photo-1210009.jpeg',
    priceMin:80, priceMax:150, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Любовь, страсть, совершенство', scent:'средний',
    colors:['красный','розовый','белый','жёлтый'], isDried:false,
    note:'Крупный бутон, стебель 60–90 см. Самый популярный цветок Киева круглый год.' },
  { id:'f2', plate:'02', name:'Тюльпан', nameLat:'Tulipa',
    img:'https://images.pexels.com/photos/31775829/pexels-photo-31775829.jpeg',
    priceMin:35, priceMax:70, seasons:[2,3,4,5],
    meaning:'Весна, нежная любовь, новое начало', scent:'слабый',
    colors:['красный','розовый','белый','жёлтый','фиолетовый'], isDried:false,
    note:'Пик сезона — март–апрель. В феврале и мае дороже.' },
  { id:'f3', plate:'03', name:'Пион', nameLat:'Paeonia',
    img:'https://images.pexels.com/photos/32312154/pexels-photo-32312154.jpeg',
    priceMin:100, priceMax:200, seasons:[5,6],
    meaning:'Процветание, счастье, богатство', scent:'сильный',
    colors:['розовый','белый','красный','коралловый'], isDried:false,
    note:'Любимец флористов. Сезон очень короткий — успейте.' },
  { id:'f4', plate:'04', name:'Хризантема', nameLat:'Chrysanthemum',
    img:'https://images.pexels.com/photos/34668695/pexels-photo-34668695.jpeg',
    priceMin:40, priceMax:80, seasons:[8,9,10,11,12],
    meaning:'Долголетие, верность, оптимизм', scent:'слабый',
    colors:['белый','жёлтый','розовый','фиолетовый'], isDried:false,
    note:'Стоит в вазе до 3 недель. Королева осени.' },
  { id:'f5', plate:'05', name:'Кустовая роза', nameLat:'Rosa multiflora',
    img:'https://images.pexels.com/photos/36051030/pexels-photo-36051030.jpeg',
    priceMin:60, priceMax:120, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Нежность, изящество, женственность', scent:'средний',
    colors:['розовый','белый','кремовый','персиковый'], isDried:false,
    note:'Несколько бутонов на одном стебле — выглядит пышно.' },
  { id:'f6', plate:'06', name:'Гортензия', nameLat:'Hydrangea',
    img:'https://images.pexels.com/photos/32057303/pexels-photo-32057303.jpeg',
    priceMin:120, priceMax:250, seasons:[6,7,8,9],
    meaning:'Искренность, благодарность, красота', scent:'слабый',
    colors:['синий','розовый','белый','фиолетовый'], isDried:true,
    note:'Огромная шапка соцветий. Отлично сохнет для сухоцветов.' },
  { id:'f7', plate:'07', name:'Эустома', nameLat:'Eustoma (Lisianthus)',
    img:'https://images.pexels.com/photos/7462761/pexels-photo-7462761.jpeg',
    priceMin:50, priceMax:100, seasons:[5,6,7,8,9,10],
    meaning:'Утончённость, признательность', scent:'слабый',
    colors:['фиолетовый','белый','розовый','кремовый'], isDried:false,
    note:'Похожа на розу, но воздушнее. Второе имя — лизиантус.' },
  { id:'f8', plate:'08', name:'Лаванда', nameLat:'Lavandula',
    img:'https://images.pexels.com/photos/12686034/pexels-photo-12686034.jpeg',
    priceMin:30, priceMax:60, seasons:[6,7,8],
    meaning:'Спокойствие, чистота, преданность', scent:'сильный',
    colors:['фиолетовый','синий'], isDried:true,
    note:'Прекрасный аромат, идеально сохнет. Прованс в Киеве.' },
  { id:'f9', plate:'09', name:'Нарцисс', nameLat:'Narcissus',
    img:'https://images.pexels.com/photos/31377567/pexels-photo-31377567.jpeg',
    priceMin:25, priceMax:45, seasons:[3,4],
    meaning:'Новое начало, весна, любовь к себе', scent:'сильный',
    colors:['белый','жёлтый'], isDried:false,
    note:'Один из первых весенних цветов. Сильный, узнаваемый аромат.' },
  { id:'f10', plate:'10', name:'Ирис', nameLat:'Iris',
    img:'https://images.pexels.com/photos/34630705/pexels-photo-34630705.jpeg',
    priceMin:45, priceMax:80, seasons:[4,5,8,9],
    meaning:'Мудрость, вера, надежда', scent:'средний',
    colors:['фиолетовый','синий','белый','жёлтый'], isDried:false,
    note:'Символ Флоренции. Цветёт дважды в году.' },
  { id:'f11', plate:'11', name:'Лилия', nameLat:'Lilium',
    img:'https://images.pexels.com/photos/13019690/pexels-photo-13019690.jpeg',
    priceMin:80, priceMax:140, seasons:[6,7,8,9],
    meaning:'Чистота, невинность, величие', scent:'сильный',
    colors:['белый','розовый','оранжевый','жёлтый'], isDried:false,
    note:'Очень ароматная. Осторожно с пыльцой и кошками.' },
  { id:'f12', plate:'12', name:'Гвоздика', nameLat:'Dianthus caryophyllus',
    img:'https://images.pexels.com/photos/11864710/pexels-photo-11864710.jpeg',
    priceMin:30, priceMax:55, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Уважение, восхищение, любовь матери', scent:'средний',
    colors:['красный','розовый','белый','фиолетовый'], isDried:false,
    note:'Долгожитель в вазе — до 2 недель.' },
  { id:'f13', plate:'13', name:'Ромашка', nameLat:'Leucanthemum vulgare',
    img:'https://images.pexels.com/photos/34210772/pexels-photo-34210772.jpeg',
    priceMin:20, priceMax:40, seasons:[6,7,8],
    meaning:'Невинность, чистота, простота', scent:'слабый',
    colors:['белый'], isDried:true,
    note:'Символ лета и беззаботности. Можно сушить.' },
  { id:'f14', plate:'14', name:'Мак', nameLat:'Papaver',
    img:'https://images.pexels.com/photos/17237540/pexels-photo-17237540.jpeg',
    priceMin:30, priceMax:60, seasons:[5,6],
    meaning:'Память, утешение, нежность', scent:'слабый',
    colors:['красный','оранжевый','розовый','белый'], isDried:false,
    note:'Очень нежный — лепестки опадают быстро.' },
  { id:'f15', plate:'15', name:'Астра', nameLat:'Aster',
    img:'https://images.pexels.com/photos/35799832/pexels-photo-35799832.jpeg',
    priceMin:30, priceMax:60, seasons:[8,9,10],
    meaning:'Терпение, элегантность, любовь', scent:'слабый',
    colors:['фиолетовый','розовый','белый','синий'], isDried:false,
    note:'Народный осенний цветок Украины.' },
  { id:'f16', plate:'16', name:'Фрезия', nameLat:'Freesia',
    img:'https://images.pexels.com/photos/15872058/pexels-photo-15872058.jpeg',
    priceMin:50, priceMax:90, seasons:[2,3,4,5,10,11],
    meaning:'Доверие, дружба, невинность', scent:'сильный',
    colors:['белый','жёлтый','розовый','фиолетовый'], isDried:false,
    note:'Один из самых ароматных срезанных цветов.' },
  { id:'f17', plate:'17', name:'Гербера', nameLat:'Gerbera',
    img:'https://images.pexels.com/photos/37632004/pexels-photo-37632004.jpeg',
    priceMin:45, priceMax:80, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Радость, оптимизм, бодрость', scent:'слабый',
    colors:['красный','розовый','оранжевый','жёлтый','белый'], isDried:false,
    note:'Яркая и жизнерадостная — круглый год.' },
  { id:'f18', plate:'18', name:'Орхидея', nameLat:'Orchidaceae',
    img:'https://images.pexels.com/photos/8503261/pexels-photo-8503261.jpeg',
    priceMin:200, priceMax:400, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Роскошь, изысканность, экзотика', scent:'слабый',
    colors:['белый','фиолетовый','розовый','жёлтый'], isDried:false,
    note:'Цена за ветку. Очень долго стоит в вазе.' },
  { id:'f19', plate:'19', name:'Подсолнух', nameLat:'Helianthus annuus',
    img:'https://images.pexels.com/photos/34537615/pexels-photo-34537615.jpeg',
    priceMin:40, priceMax:80, seasons:[7,8,9],
    meaning:'Верность, оптимизм, солнце', scent:'слабый',
    colors:['жёлтый','оранжевый'], isDried:true,
    note:'Символ Украины. Хорошо сохнет.' },
  { id:'f20', plate:'20', name:'Космея', nameLat:'Cosmos bipinnatus',
    img:'https://images.pexels.com/photos/29826505/pexels-photo-29826505.jpeg',
    priceMin:25, priceMax:45, seasons:[8,9,10],
    meaning:'Лёгкость, женственность, гармония', scent:'слабый',
    colors:['розовый','белый','фиолетовый'], isDried:true,
    note:'Нежная и воздушная. Хорошо смотрится в полевых букетах.' },
  { id:'f21', plate:'21', name:'Ранункулюс', nameLat:'Ranunculus',
    img:'https://images.pexels.com/photos/36534313/pexels-photo-36534313.jpeg',
    priceMin:80, priceMax:150, seasons:[3,4,5],
    meaning:'Очарование, притяжение, привязанность', scent:'слабый',
    colors:['розовый','белый','красный','жёлтый','оранжевый'], isDried:false,
    note:'Похож одновременно на розу и пион — фаворит весны.' },
  { id:'f22', plate:'22', name:'Дельфиниум', nameLat:'Delphinium',
    img:'https://images.pexels.com/photos/25328815/pexels-photo-25328815.jpeg',
    priceMin:60, priceMax:120, seasons:[6,7],
    meaning:'Великодушие, весёлость, воздушность', scent:'слабый',
    colors:['синий','фиолетовый','белый','розовый'], isDried:true,
    note:'Высокие голубые соцветия — добавляют объём букету.' },
  { id:'f23', plate:'23', name:'Сухоцветы (микс)', nameLat:'Dried flowers mix',
    img:'https://images.pexels.com/photos/15575099/pexels-photo-15575099.jpeg',
    priceMin:25, priceMax:50, seasons:[1,2,3,4,5,6,7,8,9,10,11,12],
    meaning:'Память, вечность, домашний уют', scent:'слабый',
    colors:['бежевый','коричневый','кремовый'], isDried:true,
    note:'Пампасная трава, статица, лагурус, гипсофила, лунария.' },
];

const BOUQUETS_DATA = [
  { id:'b1', plate:'01', name:'Свадебный каскад', category:'wedding',
    img:'https://images.pexels.com/photos/31046060/pexels-photo-31046060.jpeg',
    priceMin:2500, priceMax:5000, colors:['белый','кремовый','розовый'],
    meaning:'Элегантность, начало совместного пути',
    note:'Пионы, розы, эустома, гортензия, зелень. Удлинённая каскадная форма.' },
  { id:'b2', plate:'02', name:'Монобукет из роз', category:'mono',
    img:'https://images.pexels.com/photos/37408605/pexels-photo-37408605.jpeg',
    priceMin:800, priceMax:1500, colors:['красный','розовый'],
    meaning:'Классика выражения любви',
    note:'25 эквадорских роз 60–80 см в крафте или сетке.' },
  { id:'b3', plate:'03', name:'Коробка с пионами', category:'box',
    img:'https://images.pexels.com/photos/30828535/pexels-photo-30828535.jpeg',
    priceMin:1200, priceMax:2500, colors:['розовый','белый'],
    meaning:'Роскошь, эффектный сюрприз',
    note:'Круглая шляпная коробка, 15–25 пионов с зеленью.' },
  { id:'b4', plate:'04', name:'Праздничная корзина', category:'basket',
    img:'https://images.pexels.com/photos/17376476/pexels-photo-17376476.jpeg',
    priceMin:1500, priceMax:3000, colors:['разноцветный'],
    meaning:'Торжество, изобилие',
    note:'Плетёная корзина, смешанная флористика, оазис.' },
  { id:'b5', plate:'05', name:'Летний микс', category:'holiday',
    img:'https://images.pexels.com/photos/1479718/pexels-photo-1479718.jpeg',
    priceMin:600, priceMax:1200, colors:['жёлтый','оранжевый'],
    meaning:'Радость, лёгкость, ощущение лета',
    note:'Подсолнухи, ромашки, герберы, дельфиниум.' },
  { id:'b6', plate:'06', name:'Монобукет из хризантем', category:'mono',
    img:'https://images.pexels.com/photos/13714468/pexels-photo-13714468.jpeg',
    priceMin:500, priceMax:900, colors:['белый','жёлтый'],
    meaning:'Долголетие, верность',
    note:'7–11 кустовых хризантем с эвкалиптом.' },
  { id:'b7', plate:'07', name:'Сухоцветный букет', category:'holiday',
    img:'https://images.pexels.com/photos/6046207/pexels-photo-6046207.jpeg',
    priceMin:400, priceMax:800, colors:['бежевый','коричневый'],
    meaning:'Вечность, бохо-эстетика',
    note:'Пампасная трава, статица, лаванда, лагурус. Стоит вечно.' },
  { id:'b8', plate:'08', name:'Нежный весенний', category:'holiday',
    img:'https://images.pexels.com/photos/31844107/pexels-photo-31844107.jpeg',
    priceMin:700, priceMax:1400, colors:['розовый','белый'],
    meaning:'Весна, обновление, нежность',
    note:'Тюльпаны, нарциссы, ранункулюс, фрезия.' },
  { id:'b9', plate:'09', name:'Монобукет тюльпанов', category:'mono',
    img:'https://images.pexels.com/photos/32661864/pexels-photo-32661864.jpeg',
    priceMin:350, priceMax:700, colors:['красный','розовый','белый'],
    meaning:'Признание в любви',
    note:'21–51 тюльпан, по сезону (февраль–май).' },
  { id:'b10', plate:'10', name:'Букет невесты', category:'wedding',
    img:'https://images.pexels.com/photos/28115373/pexels-photo-28115373.jpeg',
    priceMin:1500, priceMax:3500, colors:['белый','кремовый'],
    meaning:'Чистота, новое начало',
    note:'Классический круглый букет: розы, пионы, эустома, гипсофила.' },
];

const ARRANGEMENTS_DATA = [
  { id:'a1', plate:'01', name:'Нежный романтик', flowers:['Пион','Роза Эквадор','Эустома','Гипсофила'],
    img:'https://images.pexels.com/photos/32763241/pexels-photo-32763241.jpeg',
    priceMin:1200, priceMax:2000, seasons:[5,6], colors:['розовый','белый'],
    note:'Пудровая нежно-розовая гамма для романтических поводов.' },
  { id:'a2', plate:'02', name:'Летний взрыв', flowers:['Подсолнух','Ромашка','Гербера','Дельфиниум'],
    img:'https://images.pexels.com/photos/9550936/pexels-photo-9550936.jpeg',
    priceMin:700, priceMax:1300, seasons:[7,8], colors:['жёлтый','синий'],
    note:'Яркие, насыщенные летние оттенки. Энергия солнца.' },
  { id:'a3', plate:'03', name:'Осенний уют', flowers:['Хризантема','Астра','Гербера','Космея'],
    img:'https://images.pexels.com/photos/34658018/pexels-photo-34658018.jpeg',
    priceMin:600, priceMax:1100, seasons:[9,10], colors:['оранжевый','фиолетовый'],
    note:'Тёплая осенняя палитра — терракот, бордо, охра.' },
  { id:'a4', plate:'04', name:'Весенняя сказка', flowers:['Тюльпан','Нарцисс','Ранункулюс','Фрезия'],
    img:'https://images.pexels.com/photos/36865677/pexels-photo-36865677.jpeg',
    priceMin:500, priceMax:1000, seasons:[3,4,5], colors:['розовый','жёлтый'],
    note:'Свежесть, аромат и пастельные краски марта.' },
  { id:'a5', plate:'05', name:'Фиолетовая мечта', flowers:['Гортензия','Дельфиниум','Лаванда','Эустома'],
    img:'https://images.pexels.com/photos/35421156/pexels-photo-35421156.jpeg',
    priceMin:900, priceMax:1800, seasons:[6,7], colors:['фиолетовый','синий'],
    note:'Холодная лавандовая гамма с ароматом прованса.' },
  { id:'a6', plate:'06', name:'Бохо-сухоцветы', flowers:['Пампасная трава','Лаванда','Подсолнух','Космея'],
    img:'https://images.pexels.com/photos/33588173/pexels-photo-33588173.jpeg',
    priceMin:400, priceMax:800, seasons:[1,2,3,4,5,6,7,8,9,10,11,12], colors:['бежевый','коричневый'],
    note:'Вечный букет — не вянет, не требует воды.' },
];

const CATEGORY_LABELS = {
  wedding: 'Свадебный', holiday: 'Праздничный',
  mono: 'Монобукет', box: 'Коробка', basket: 'Корзина',
};

const MONTH_NAMES = ['Январь','Февраль','Март','Апрель','Май','Июнь',
                     'Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const MONTH_SHORT = ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'];
const MONTH_LAT   = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

const SEASON_GROUPS = {
  winter: [12, 1, 2], spring: [3, 4, 5], summer: [6, 7, 8], autumn: [9, 10, 11],
  year:   [1,2,3,4,5,6,7,8,9,10,11,12],
};
const SEASON_DATA = [
  { key:'winter', label:'Winter', ru:'Зима',  months:[12, 1, 2] },
  { key:'spring', label:'Spring', ru:'Весна', months:[3, 4, 5] },
  { key:'summer', label:'Summer', ru:'Лето',  months:[6, 7, 8] },
  { key:'autumn', label:'Autumn', ru:'Осень', months:[9, 10, 11] },
];

/* Seasonal advice for the "what to gift" suggestion */
const SEASON_ADVICE = {
  1:  'Январь — время тепличных роз и орхидей. Добавь зелени эвкалипта для свежести.',
  2:  'Появились первые тюльпаны и фрезии — весна на подходе. Самое время для нежных букетов.',
  3:  'Март — пик тюльпанов и нарциссов. Классика 8 марта и при этом доступно.',
  4:  'Ранункулюс и ирисы в самом соку. Собери пастельный весенний микс.',
  5:  'Пионы! Главная роскошь мая. Бери 5–7 штук, пока сезон не закончился.',
  6:  'Лето открывают пионы, гортензия и лаванда. Ароматный фиолетовый микс — беспроигрышно.',
  7:  'Подсолнухи, лилии и гортензия. Яркие солнечные букеты под настроение.',
  8:  'Конец лета — астры, космея, подсолнухи. Полевое настроение и доступные цены.',
  9:  'Хризантемы и астры открывают осень. Тёплая терракотовая гамма.',
  10: 'Золотая осень: хризантемы держатся до 3 недель — отличное соотношение цены и стойкости.',
  11: 'Хризантемы и фрезии. Хороший момент для сухоцветов к зимнему декору.',
  12: 'Декабрь — розы, орхидеи и сухоцветы. Собери вечный бохо-букет к праздникам.',
};

const LS_KEY = 'kyivFloraAtlas_v2';
const VERSION = '2.1';
const LAST_UPDATE = '27 мая 2026';
